// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdzFF-FbtZ593uoB0DoGksX3n24-h87O4',
    appId: '1:776843056656:web:5f0034af8f3e0dcdccdc95',
    messagingSenderId: '776843056656',
    projectId: 'my-first-fb',
    authDomain: 'my-first-fb-d2c49.firebaseapp.com',
    storageBucket: 'my-first-fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiJJV1qIWaHjLB7vafyNryTvR0LnvLzXk',
    appId: '1:776843056656:android:fcef9afc41a55747ccdc95',
    messagingSenderId: '776843056656',
    projectId: 'my-first-fb',
    storageBucket: 'my-first-fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw8AgpWoK_IrRhX4JGG1SXErA--YTVf9U',
    appId: '1:776843056656:ios:8458860f6cc5a51eccdc95',
    messagingSenderId: '776843056656',
    projectId: 'my-first-fb',
    storageBucket: 'my-first-fb.appspot.com',
    iosBundleId: 'com.example.firebaseSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw8AgpWoK_IrRhX4JGG1SXErA--YTVf9U',
    appId: '1:776843056656:ios:a0825ec092990f1eccdc95',
    messagingSenderId: '776843056656',
    projectId: 'my-first-fb',
    storageBucket: 'my-first-fb.appspot.com',
    iosBundleId: 'com.example.firebaseSample.RunnerTests',
  );
}
